spring:
  http:
    multipart:
      max-file-size: 100Mb
  freemarker:
    allow-request-override: false
    cache: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yx?characterEncoding=utf-8&useSSL=false
server:
  port: 8080
